A first attempt at ignoring draft PRs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -24,6 +24,8 @@
 # We define the following GitLab pipeline variables:
 variables:
   MP_BRANCH: "develop"
+  GITHUB_PROJECT_NAME: "raja"
+  GITHUB_PROJECT_ORG: "llnl"
 # Use a service user to run CI. This prevents from running pipelines as an
 # actual user.
   LLNL_SERVICE_USER: ""
@@ -41,8 +43,38 @@ variables:
 
 # High level stages
 stages:
+  - should-we-test
   - build-and-test
   - multi_project
+
+# This job should fail if we don’t want the pipeline to run.
+# Here, we make sure the pipeline fails if the PR is a draft.
+should-we-test-check:
+  stage: should-we-test
+  script:
+    - |
+      curl --header "authorization: Bearer ${GITHUB_TOKEN}" -X POST -d " \
+      { \
+        \"query\": \"query { \
+                             repository(name: \\\"${GITHUB_PROJECT_NAME}\\\", owner: \\\"${GITHUB_PROJECT_ORG}\\\") { \
+                               pullRequests(last: 1, headRefName: \\\"${CI_COMMIT_REF_NAME}\\\") { \
+                                 nodes { \
+                                   number, \
+                                   isDraft \
+                                 } \
+                               } \
+                             } \
+                          }\" \
+      } \
+      " https://api.github.com/graphql > data.json 2> /dev/null
+      if $(jq '.data.repository.pullRequests.nodes[].isDraft' data.json)
+      then
+        curl --url "https://api.github.com/repos/${GITHUB_PROJECT_ORG}/${GITHUB_PROJECT_NAME}/statuses/${CI_COMMIT_SHA}" \
+             --header 'Content-Type: application/json' \
+             --header "authorization: Bearer ${GITHUB_TOKEN}" \
+             --data "{ \"state\": \"failed\", \"target_url\": \"${CI_PIPELINE_URL}\", \"description\": \"GitLab: Skipped Draft PR\", \"context\": \"ci/gitlab/skipped-draft-pr\" }"
+        exit 1
+      fi
 
 # Template for jobs triggering a build-and-test sub-pipelines:
 .build-and-test:
