Renew CI specs per https://github.com/LLNL/radiuss-shared-ci/issues/15 + remove local overrides + update local specs

diff --git a/.gitlab/lassen-build-and-test-extra.yml b/.gitlab/lassen-build-and-test-extra.yml
--- a/.gitlab/lassen-build-and-test-extra.yml
+++ b/.gitlab/lassen-build-and-test-extra.yml
@@ -12,94 +12,94 @@
 # We keep ${PROJECT_<MACHINE>_VARIANTS} and ${PROJECT_<MACHINE>_DEPS} So that
 # the comparison with the original job is easier.
 
-# Overriding shared spec: Allow failures
-ibm_clang_9_0_0:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %clang@ibm.9.0.0 ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-  allow_failure: true
-
-# Overriding shared spec: Allow failures
-ibm_clang_9_0_0_gcc_8_3_1:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %clang@ibm.9.0.0 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-  allow_failure: true
-
-# Overriding shared spec: Extra flags
-gcc_8_3_1:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %gcc@8.3.1 cxxflags==\"-finline-functions -finline-limit=20000\" cflags==\"-finline-functions -finline-limit=20000\" ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-
-# Overriding shared spec: Longer allocation + Allow failures
-pgi_20_4_gcc_8_3_1:
-  extends: .build_and_test_on_lassen
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %pgi@20.4 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
-    LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 80"
-  allow_failure: true
-
-# Overriding shared spec: Extra flags
-xl_16_1_1_12:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %xl@16.1.1.12 cxxflags==\"-qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-
-# Overriding shared spec: Extra flags
-xl_16_1_1_12_gcc_8_3_1:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-
-# Overriding shared spec: Allow failures
-ibm_clang_9_0_0_gcc_8_3_1_cuda_10_1_168:
-  extends: .build_and_test_on_lassen
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %clang@ibm.9.0.0 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ^cuda@10.1.168 ${PROJECT_LASSEN_DEPS}"
-  allow_failure: true
-
-# Overriding shared spec: Longer allocation + Extra flags + Allow failure + Updated cuda
-xl_16_1_1_12_cuda_11_1_1:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"-qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cuda_arch=70 ^cuda@11.1.0 ${PROJECT_LASSEN_DEPS}"
-    LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 120"
-  allow_failure: true
-  extends: .build_and_test_on_lassen
-
-# Overriding shared spec: Deactivated spec. This spec will be removed soon.
-xl_16_1_1_12_gcc_7_3_1_cuda_10_1_168:
-  variables:
-    SPEC: "${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1\" ^cuda@10.1.168 ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-  script:
-    - |
-      echo -e "\e[31mDeactivated spec !\e[0m"
-      echo -e "\e[31m${SPEC}\e[0m"
-      echo -e "\e[31mRAJA won’t build with Cuda < 11.1.0 due to a known issue.\e[0m"
-    - exit 1
-  allow_failure: true
-
-# Overriding shared spec: Deactivated spec. This spec will be removed soon.
-xl_16_1_1_12_gcc_8_3_1_cuda_11_0_2:
-  variables:
-    SPEC: "${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ^cuda@11.0.2 ${PROJECT_LASSEN_DEPS}"
-  extends: .build_and_test_on_lassen
-  script:
-    - |
-      echo -e "\e[31mDeactivated spec !\e[0m"
-      echo -e "\e[31m${SPEC}\e[0m"
-      echo -e "\e[31mRAJA won’t build with Cuda < 11.0.2 due to a known issue.\e[0m"
-    - exit 1
-  allow_failure: true
-
-# Overriding shared spec: Longer allocation + Extra flags + Allow failure + Updated cuda
-xl_16_1_1_12_gcc_8_3_1_cuda_11_1_0:
-  variables:
-    SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cuda_arch=70 ^cuda@11.1.0 ${PROJECT_LASSEN_DEPS}"
-    LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 120"
-  allow_failure: true
-  extends: .build_and_test_on_lassen
+##  # Overriding shared spec: Allow failures
+##  ibm_clang_9_0_0:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %clang@ibm.9.0.0 ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Allow failures
+##  ibm_clang_9_0_0_gcc_8_3_1:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %clang@ibm.9.0.0 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Extra flags
+##  gcc_8_3_1:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %gcc@8.3.1 cxxflags==\"-finline-functions -finline-limit=20000\" cflags==\"-finline-functions -finline-limit=20000\" ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##  
+##  # Overriding shared spec: Longer allocation + Allow failures
+##  pgi_20_4_gcc_8_3_1:
+##    extends: .build_and_test_on_lassen
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %pgi@20.4 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
+##      LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 80"
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Extra flags
+##  xl_16_1_1_12:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %xl@16.1.1.12 cxxflags==\"-qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##  
+##  # Overriding shared spec: Extra flags
+##  xl_16_1_1_12_gcc_8_3_1:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##  
+##  # Overriding shared spec: Allow failures
+##  ibm_clang_9_0_0_gcc_8_3_1_cuda_10_1_168:
+##    extends: .build_and_test_on_lassen
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %clang@ibm.9.0.0 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ^cuda@10.1.168 ${PROJECT_LASSEN_DEPS}"
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Longer allocation + Extra flags + Allow failure + Updated cuda
+##  xl_16_1_1_12_cuda_11_1_1:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"-qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cuda_arch=70 ^cuda@11.1.0 ${PROJECT_LASSEN_DEPS}"
+##      LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 120"
+##    allow_failure: true
+##    extends: .build_and_test_on_lassen
+##  
+##  # Overriding shared spec: Deactivated spec. This spec will be removed soon.
+##  xl_16_1_1_12_gcc_7_3_1_cuda_10_1_168:
+##    variables:
+##      SPEC: "${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1\" ^cuda@10.1.168 ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##    script:
+##      - |
+##        echo -e "\e[31mDeactivated spec !\e[0m"
+##        echo -e "\e[31m${SPEC}\e[0m"
+##        echo -e "\e[31mRAJA won’t build with Cuda < 11.1.0 due to a known issue.\e[0m"
+##      - exit 1
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Deactivated spec. This spec will be removed soon.
+##  xl_16_1_1_12_gcc_8_3_1_cuda_11_0_2:
+##    variables:
+##      SPEC: "${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" ^cuda@11.0.2 ${PROJECT_LASSEN_DEPS}"
+##    extends: .build_and_test_on_lassen
+##    script:
+##      - |
+##        echo -e "\e[31mDeactivated spec !\e[0m"
+##        echo -e "\e[31m${SPEC}\e[0m"
+##        echo -e "\e[31mRAJA won’t build with Cuda < 11.0.2 due to a known issue.\e[0m"
+##      - exit 1
+##    allow_failure: true
+##  
+##  # Overriding shared spec: Longer allocation + Extra flags + Allow failure + Updated cuda
+##  xl_16_1_1_12_gcc_8_3_1_cuda_11_1_0:
+##    variables:
+##      SPEC: " ${PROJECT_LASSEN_VARIANTS} +cuda %xl@16.1.1.12 cxxflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -qthreaded -std=c++14 -O3 -qstrict -qxlcompatmacros -qlanglvl=extended0x -qalias=noansi -qhot -qpic -qsmp=omp -qsuppress=1500-029 -qsuppress=1500-036\" cflags==\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cuda_arch=70 ^cuda@11.1.0 ${PROJECT_LASSEN_DEPS}"
+##      LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 120"
+##    allow_failure: true
+##    extends: .build_and_test_on_lassen
 
 
 ############
@@ -108,29 +108,6 @@ xl_16_1_1_12_gcc_8_3_1_cuda_11_1_0:
 # We do not recommend using ${PROJECT_<MACHINE>_VARIANTS} and
 # ${PROJECT_<MACHINE>_DEPS} in the extra jobs. There is no reason not to fully
 # describe the spec here.
-
-##########
-# CPU ONLY
-##########
-
-clang_14_0_5:
-  variables:
-    SPEC: " ~shared +openmp +tests %clang@14.0.5"
-  extends: .build_and_test_on_lassen
-
-##########
-# CUDA
-##########
-
-clang_12_0_1_cuda_11_5_0:
-  variables:
-    SPEC: " ~shared +openmp +tests +cuda cuda_arch=70 %clang@12.0.1 ^cuda@11.5.0"
-  extends: .build_and_test_on_lassen
-
-gcc_8_3_1_cuda_11_1_0:
-  variables:
-    SPEC: " ~shared +openmp +tests +cuda %gcc@8.3.1 cuda_arch=70 ^cuda@11.1.0"
-  extends: .build_and_test_on_lassen
 
 gcc_8_3_1_cuda_11_5_0_ats_disabled:
   extends: .build_and_test_on_lassen
@@ -144,7 +121,7 @@ gcc_8_3_1_cuda_11_5_0_ats_disabled:
 
 clang_13_0_1_libcpp:
   variables:
-    SPEC: " ~shared +openmp +tests %clang@13.0.1+libcpp"
+    SPEC: " ~shared +openmp +tests +libcpp %clang@13.0.1"
   extends: .build_and_test_on_lassen
 
 clang_14_0_5_asan:
@@ -153,7 +130,7 @@ clang_14_0_5_asan:
     ASAN_OPTIONS: "detect_leaks=1"
   extends: .build_and_test_on_lassen
 
-gcc_8_3_1_cuda_10_1_168_desul_atomics:
+gcc_8_3_1_cuda_10_1_243_desul_atomics:
   variables:
-    SPEC: " ~shared +openmp +tests +cuda +desul %gcc@8.3.1 cuda_arch=70 ^cuda@10.1.168"
+    SPEC: " ~shared +openmp +tests +cuda +desul %gcc@8.3.1 cuda_arch=70 ^cuda@10.1.243"
   extends: .build_and_test_on_lassen
